version: '3'
services:
  web:
    container_name: usermanager
    restart: always
    build: .
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo_db
    links:
      - mongo_db
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"